services:
  postgres:
    container_name: db
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    expose:
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres_data: